Repository tuwien-csd/damap-backend, pull requests merged in 2022-12, with the labels that each got.

#67 change VARCHAR2 to CLOBs for description properties
  src/main/java/at/ac/tuwien/damap/rest/dmp/domain/DatasetDO.java
  src/main/java/at/ac/tuwien/damap/rest/dmp/domain/DmpDO.java
  src/main/java/at/ac/tuwien/damap/rest/dmp/domain/ProjectDO.java
  src/main/java/at/ac/tuwien/damap/rest/openaire/mapper/OpenAireMapper.java
  src/main/resources/db/changeLog.yaml
Labels: bug

#68 Allow frontend to request export for a specific template,
  src/main/java/at/ac/tuwien/damap/conversion/ExportFWFTemplate.java
  src/main/java/at/ac/tuwien/damap/conversion/ExportScienceEuropeTemplate.java
  src/main/java/at/ac/tuwien/damap/conversion/ExportTemplateBroker.java
  src/main/java/at/ac/tuwien/damap/enums/ETemplateType.java
  src/main/java/at/ac/tuwien/damap/rest/DmpDocumentResource.java
  src/test/java/at/ac/tuwien/damap/rest/DmpDocumentResourceTest.java
Labels: enhancement

#69 Add DMP editor functionality
  src/main/java/at/ac/tuwien/damap/rest/AccessResource.java
  src/main/java/at/ac/tuwien/damap/rest/access/domain/AccessDO.java
  src/main/java/at/ac/tuwien/damap/rest/access/mapper/AccessMapper.java
  src/main/java/at/ac/tuwien/damap/rest/access/service/AccessService.java
  src/main/java/at/ac/tuwien/damap/rest/dmp/mapper/MapperService.java
  src/main/java/at/ac/tuwien/damap/validation/AccessValidator.java
  src/test/java/at/ac/tuwien/damap/rest/AccessResourceTest.java
Labels: enhancement, major
